apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: presales-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: app
          image: walber7/spring-boot-hello:166
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
